--[[
    SampleHub Loader - KEY PLACEHOLDER
    ===================================
    DO NOT EDIT THIS FILE MANUALLY!
    Your key will be automatically inserted by the bot.
]]

-- ⚠️ BOT WILL REPLACE THIS WITH USER'S UNIQUE KEY
lp_key = "PLACEHOLDER_KEY_HERE"

-- ⚠️ DO NOT MODIFY ANYTHING BELOW THIS LINE
-- ============================================

local f, c, v = "12125701348483376783", http and http.request or request, function(h) 
    while(task.wait()) do
        pcall(function() 
            game:GetService("Players").LocalPlayer:Kick(h)
            local v = game:GetService("CoreGui").RobloxPromptGui.promptOverlay.ErrorPrompt
            v.TitleFrame.ErrorTitle.Text = "LuaProt"
            v.MessageArea.ErrorFrame.ErrorMessage.Text = h
        end)
    end
end

local b, o, h, k, d
o = {"eu-1", "as-1", "us-1"}

h, k = pcall(c, {Url = "https://eu-1.luaprot.net/api/v1/nodes/get"})
if(h and k and k.StatusCode == 200) then
    pcall(function() 
        d = game:GetService("HttpService"):JSONDecode(k.Body)
    end)
    if(d and d.success and d.node) then
        for i, n in o do
            if(n == d.node) then
                table.insert(o, 1, table.remove(o, i))
                break
            end
        end
    end
end

for i = 1, 5 do
    if(b) then break end
    for _, p in o do
        local r, y = os.clock()
        task.spawn(pcall, function() 
            y = c({Url = "https://" .. p .. ".luaprot.net/api/v2/loader/get?key=" .. lp_key .. "&scriptId=" .. f})
        end)
        repeat task.wait() until(os.clock() - r > 5 or y)
        if(y and ({[200] = i, [201] = i})[y.StatusCode]) then
            LP_NODE = p
            b = loadstring(y.Body)
            if(b) then break end
        end
    end
end

if(b) then
    b(LP_NODE)
else
    v("V2 loader failed to load script. Report this and try again later!")
end
